# Generated by Django 4.1.2 on 2022-10-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_organizer_match_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.organizer', verbose_name='Organizer'),
        ),
    ]
