# Generated by Django 4.1.2 on 2022-10-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('matches', '0003_alter_match_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.sports'),
        ),
    ]
