# Generated by Django 4.1.2 on 2022-10-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_session_year_matchdate_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6),
        ),
    ]
