# Generated by Django 4.1.2 on 2022-10-28 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('matches', '0006_match_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='organizer',
        ),
        migrations.AddField(
            model_name='matchdate',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.organizer', verbose_name='Organizer'),
        ),
        migrations.CreateModel(
            name='SingleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6)),
                ('match_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchdate')),
                ('sports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.sports')),
            ],
        ),
    ]
