# Generated by Django 4.1.2 on 2022-10-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_match_game_date_match_game_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
