# Generated by Django 4.1.2 on 2022-10-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_singlematch_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
