# Generated by Django 4.1.2 on 2022-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sports_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/icons'),
        ),
    ]
