# Generated by Django 4.1.2 on 2022-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_description_remove_news_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
